### ISSUE TITLE
How to change from Japanese based to English based

### ISSUE THREAD

**Issue by shinokada** [Paperist/docker-alpine-texlive-ja#19]
Hi,

I'd like to know how to change from Japanese based to English based.
Which code do I need to update?

Thank you.

**Comment by 3846masa** [comment]
If you want an texlive image without packages related to japanese,

1. clone this repository
2. remove `collection-langjapanese` line from Dockerfile
3. build image yourself

**Comment by shinokada** [comment]
Thank you for your reply.
One more question.

In Dockerfile:

```
# LaTeX
$latex = 'platex -synctex=1 -halt-on-error -file-line-error %O %S';
```
How can I use `latex` or `xelatex` or different one?

I tried this but it didn't work:

```
$latex = 'latex -synctex=1 -halt-on-error -file-line-error %O %S';
```

**Comment by 3846masa** [comment]
I tried latex, it's works fine.

`latexmkrc`
```perl
$latex = 'latex -halt-on-error -interaction=nonstopmode';
$dvipdf = 'dvipdfmx %O -o %D %S';
$pdf_mode = 3;
```

`main.tex`
```tex
\documentclass[12pt]{article}
\begin{document}

Hello \LaTeX

\end{document}
```

----

If you want to use another engine, you should install engine via tlmgr.

e.g. `tlmgr install collection-xetex` if you want to use xelatex.

As it is outside the scope of this repository, I am unable to provide further support.
