### ISSUE TITLE
How to watch .tex files?

### ISSUE THREAD

**Issue by kikirinrin** [Paperist/docker-alpine-texlive-ja#6]
Thanks to the answer to #2, I managed to set workflow using `latexmk` up.

I tried to watch `*.tex` file update using `-pvc` option,
 but it failed because `acroread` is not installed to the Docker image.

Would you tell me how can I install acroread to the image?

Thanks,

**Comment by kikirinrin** [comment]
I try to install `acroread` by editing `Dockerfile` like below,
 but it failed because cmd `apt-get` is not found in base image `frolvlad/alpine-glibc`.

``` sh
RUN apk --no-cache add perl wget xz tar fontconfig-dev freetype-dev && \
...;
  apk --no-cache del xz tar && \
  apt-get install acroread
```

**Comment by 3846masa** [comment]
acroread is not required to run watch mode.
You can overwrite pdf viewer via latexmkrc. (See https://mg.readthedocs.io/latexmk.html#configuration-files)

However, in Docker container, you cannot open any viewer.
You should empty `$pdf_previewer`.

```
$pdf_previewer = '';
```

**Comment by kikirinrin** [comment]
I managed to watch `.tex` file update!!

Thank you again
