### ISSUE TITLE
How to compile .tex with unicode chars when attach ./docs/ to .workdir/?

### ISSUE THREAD

**Issue by kikirinrin** [Paperist/docker-alpine-texlive-ja#7]
I'm satisfied with my `./manuscript.tex` is compiled correctly with command
`docker-compose run --rm latexmk manuscript.tex `

But I want to move `*.tex` and `*.pdf` into `./docs/` next.

I tried the procedures below but compilation failed finally.

### Move manuscript
```
mkdir docs
mv .manuscript.tex ./docs
```
### Edit `docker-compose.yml`
```
  volumes:
-    - './:/workdir'
+   - './docs/:/workdir
```
### Rebuild docker-compose
`docker-compose up -d`

### Compile `.tex`
`docker-compose run --rm latexmk manuscript.tex `

**Comment by kikirinrin** [comment]
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Latexmk: applying rule 'latex'...
Rule 'latex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'manuscript.tex'
   Non-existent destination files:
      'manuscript.dvi'
------------
Run number 1 of rule 'latex'
------------
------------
Running 'latex  -recorder  "manuscript.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./manuscript.tex
LaTeX2e <2018-12-01>
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/local/texlive/2018/texmf-dist/tex/latex/base/size11.clo))
(./manuscript.aux)

! Package inputenc Error: Unicode character マ (U+30DE)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.10 \maketitle

?

**Comment by kikirinrin** [comment]
# My trial 2 (but failed)
Use packages below
- ` \usepackage{inputenc}`: situation did not change
- `\usepackage{fontspec}`: failed because it was supported by XeLaTeX or LuaTeX

**Comment by kikirinrin** [comment]
I have no idea why compilation to `./manuscript.tex` works well but `./docs/manuscript.tex` fails with character encoding.

Thanks.

**Comment by 3846masa** [comment]
It's seems that `latexmk` cannot found `latexmkrc` file.
Please put `latexmkrc` in `./docs`.

**Comment by kikirinrin** [comment]
I managed to do that...

THANK YOU VERY MUCH
